// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconFeatherMusic: typeof import('~icons/feather/music.jsx')['default']
}
export {}
